name: shufflechat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.14.3+1
  cupertino_icons: ^1.0.1
  custom_radio_grouped_button: ^1.0.6+1
  easy_localization: ^2.3.3+1
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.2+1
  firebase_storage: ^5.2.0
  flutter_native_image: ^0.0.5+3
  flutter_phoenix: ^0.1.0
  flutter_typeahead: ^2.0.0
  flutter_xlider: ^3.4.0
  form_field_validator: ^1.0.1
  image_picker: ^0.6.7+14
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/shuffleCoin.png
    - assets/images/shuffleCoin+.png

